Day 22: KPI Design

1. Define and calculate key sales KPIs.

1.Total Revenue: The total amount of money generated from sales
SELECT SUM(SalesAmount) as TotalRevenue
FROM FactInternetSales

2.Average OrderValue: The average amount spent per order
SELECT SalesOrderNumber,
	SUM(SalesAmount)/Count(Distinct SalesOrderNumber) as AverageOrderValue
FROM FactInternetSales
GROUP BY SalesOrderNumber

3.CustomerLifetime Value: The total revenue generated by a customer over time.
SELECT CustomerKey,
	SUM(SalesAmount) as TotalRevenue
FROM FactInternetSales
GROUP BY CustomerKey
Order By TotalRevenue DESC

4.Repeat purchase rate:  Percentage of customers who made more than one purchase
WITH BASETABLE AS
(
	SELECT F.CustomerKey,
		CONCAT(C.FirstName, ' ', ISNULL(C.MiddleName + ' ', ''), C.LastName) AS CustomerFullName,
		COUNT(Distinct F.SalesOrderNumber) AS TotalOrders
		From FactInternetSales F
		LEFT JOIN DimCustomer C
		ON F.CustomerKey = C.CustomerKey
		GROUP BY F.CustomerKey,
			CONCAT(C.FirstName, ' ', ISNULL(C.MiddleName + ' ', ''), C.LastName)
		--HAVING COUNT(Distinct F.SalesOrderNumber) >1
),
FREQUENCYOFORDER AS
(
	SELECT *,
		CASE
		When TotalOrders > 1 then 'RepeatPurchase'
		Else 'SingleOrder'
		End AS FrequencyOfPurchase
	From BASETABLE
)
SELECT
	SUM(CASE
		When FrequencyOfPurchase= 'RepeatPurchase' then 1 ELSE 0 END)*100.0/Count(*)  AS RepeatePurchaseRate
FROM FREQUENCYOFORDER

5.OrderVolum:Total number of orders placed.
SELECT Count(Distinct SalesOrderNumber) as OrderVolume
FROM FactInternetSales

6.Month-over-Month Revenue Growth:The percentage increase or decrease in revenue compared to the previous month.
WITH MONTHLYREVENUE AS
(
	SELECT Datepart(Year, OrderDate) as OrderYear,
		Datepart(Month, OrderDate) as OrderMonth,
		Sum(SalesAmount) as CurrentMonthRevenue
	FROM FactInternetSales
	Group by Datepart(Year, OrderDate),
		Datepart(Month, OrderDate) 
),
MoM as
(
	SELECT *,
		Lag(CurrentMonthRevenue,1) over (Order By OrderYear,OrderMonth) as PreviousMonthRevenue
	from MONTHLYREVENUE

)
SELECT *,
(CurrentMonthRevenue-PreviousMonthRevenue)*100.0/NULLIF(PreviousMonthRevenue,0) as MoMGrowth
FROM MoM


7.Revenue by Region: Revenue generated per geographical region
SELECT G.EnglishCountryRegionName AS Region,
	SUM(F.SalesAmount) as TotalRevenue
FROM FactInternetSales F
LEFT JOIN DimGeography G
ON F.SalesTerritoryKey = G.SalesTerritoryKey
GROUP BY G.EnglishCountryRegionName
Order By TotalRevenue DESC
	
8.Top selling Product:Products generating the highest revenue or sales volume.
SELECT P.EnglishProductName AS ProductName,
	SUM(F.SalesAmount) as TotalRevenue
FROM FactInternetSales F
LEFT JOIN DimProduct P
ON F.ProductKey = P.ProductKey
GROUP BY  P.EnglishProductName
Order By TotalRevenue DESC

9.Sales decline Rate: Measures products, customers, or regions with declining sales

Sales decline Rate: Measures products,
WITH BASETABE AS
(
	SELECT P.EnglishProductName AS ProductName,
		Datepart(Year, OrderDate) as OrderYear,
		SUM(F.SalesAmount) as CurrentYearRevenue
	FROM FactInternetSales F
	LEFT JOIN DimProduct P
	ON F.ProductKey = P.ProductKey
	GROUP BY P.EnglishProductName,
		 Datepart(Year, OrderDate)
--ORDER BY  OrderYear 
) ,
PMRevenue AS
(
	SELECT *,
		LAG(CurrentYearRevenue) over (Partition By ProductName Order by OrderYear) AS PreviousYearRevenue
	FROM BASETABE
)
SELECT *,
		(CurrentYearRevenue-PreviousYearRevenue)*100.0/NULLIF(PreviousYearRevenue,0)  as RevenueGrowthRate,
		CASE
			WHEN CurrentYearRevenue<PreviousYearRevenue Then 'Declining'
			ELSE 'Growing'
			END AS SalesGrowthIndicator
FROM PMRevenue

Sales decline Rate: Measures Region
WITH CYREVENUE AS
(
	SELECT Datepart(Year, F.OrderDate) as OrderYear,
		G.EnglishCountryRegionName AS Region,
		SUM(F.SalesAmount) as CurrentYearRevenue
	FROM FactInternetSales F
	LEFT JOIN DimGeography G
	ON F.SalesTerritoryKey = G.SalesTerritoryKey
	GROUP BY G.EnglishCountryRegionName,
		Datepart(Year, F.OrderDate)
	--Order By TotalRevenue DESC
),
PYREVENUE AS
(
	SELECT *,
		LAG(CurrentYearRevenue) OVER (Partition BY Region Order By OrderYear) as PreviousYearRevenue
	FROM CYREVENUE
)
SELECT *,
	(CurrentYearRevenue-PreviousYearRevenue)*100.0/NULLIF(PreviousYearRevenue,0) AS RegionRevenueTrend,
	CASE
	WHEN CurrentYearRevenue<PreviousYearRevenue THEN 'Declining'
	ELSE 'Growing'
	END as RegionGrowthIndicator
FROM PYREVENUE

Sales decline Rate: Measures Customers
WITH BASETABLE AS
(
	SELECT Datepart(Year, F.OrderDate) As OrderYear,
		F.CustomerKey as CustomerKey,
		CONCAT(C.FirstName, ' ', ISNULL(C.MiddleName + ' ', ''), C.LastName) AS CustomerFullName,
		SUM(F.SalesAmount) AS CurrentYearRevenue
		From FactInternetSales F
		LEFT JOIN DimCustomer C
		ON F.CustomerKey = C.CustomerKey
		GROUP BY Datepart(Year, F.OrderDate),
			F.CustomerKey,
			CONCAT(C.FirstName, ' ', ISNULL(C.MiddleName + ' ', ''), C.LastName)
),
PYRevenue AS
(
	SELECT *,
		LAG(CurrentYearRevenue) OVER (Partition by CustomerKey,CustomerFullName
		Order By OrderYear) as PerviouYearRevenue
	FROM BASETABLE
)
SELECT *,
	(CurrentYearRevenue-PerviouYearRevenue)*100.0/NULLIF(PerviouYearRevenue,0) as CustomerRevenueTrend,
	CASE
	WHEN CurrentYearRevenue<PerviouYearRevenue THEN 'Declining'
	ELSE 'Growing' 
	END as CustomerRevenueIndicator
FROM PYRevenue

10.Revenue contribution: Percentage contribution of a product/customer/category to total revenue

Percentage contribution of products
WITH BASETABLE AS
(
	SELECT P.EnglishProductName AS ProductName,
		SUM(F.SalesAmount) as TotalRevenue
	FROM FactInternetSales F
	LEFT JOIN DimProduct P
	ON F.ProductKey = P.ProductKey
	GROUP BY  P.EnglishProductName
	--Order By TotalRevenue DESC
)
SELECT *,
 TotalRevenue *100.0/sum(TotalRevenue) over ()  as PercentageContributionByProduct
FROM BASETABLE

WITH BASETABLE AS
(
	SELECT G.EnglishCountryRegionName AS Region,
		SUM(F.SalesAmount) as TotalRevenue
	FROM FactInternetSales F
	LEFT JOIN DimGeography G
	ON F.SalesTerritoryKey = G.SalesTerritoryKey
	GROUP BY G.EnglishCountryRegionName
	--Order By TotalRevenue DESC
)
SELECT *,
	TotalRevenue *100.0/SUM(TotalRevenue) over () as PercentaeContributionByRegion
FROM BASETABLE

Percentage contribution of Customers
WITH BASETABLE AS
(
	SELECT C.CustomerKey,
	CONCAT(C.FirstName, ' ', ISNULL(C.MiddleName + ' ', ''), C.LastName) AS CustomerFullName,
	ISNULL(SUM(F.SalesAmount),0) as TotalRevenue
FROM DimCustomer C
LEFT JOIN FactInternetSales F
ON C.CustomerKey = F.CustomerKey
GROUP BY C.CustomerKey,
	CONCAT(C.FirstName, ' ', ISNULL(C.MiddleName + ' ', ''), C.LastName)
--Order By TotalRevenue DESC
)
SELECT *,
TotalRevenue *100.0/SUM(TotalRevenue) over () as PercentaeContributionByCustomer
FROM BASETABLE

WITH BASETABLE AS
(
	SELECT
		C.EnglishProductCategoryName As ProductCategoryName,
		SUM(F.SalesAmount) as CurrentYearSales
	FROM FactInternetSales F
	LEFT JOIN DimProduct P
	ON F.ProductKey = P.ProductKey
	LEFT JOIN DimProductSubCategory S
	ON P.ProductSubCategoryKey = S.ProductSubCategoryKey
	LEFT JOIN DimProductCategory C
	ON S.ProductCategoryKey = C.ProductCategoryKey
	GROUP BY
		C.EnglishProductCategoryName
)
SELECT ProductCategoryName,
	CurrentYearSales * 100.0/SUM(CurrentYearSales) OVER () AS PercentageContribution
FROM BASETABLE	

